import os
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from crew import resume_crew

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ResumeRequest(BaseModel):
    profile: str
    job_description: str
    theme: str = "Modern"

@app.post("/api/generate")
def generate_resume(request: ResumeRequest):
    inputs = {
        "profile": request.profile,
        "job_description": request.job_description,
        "theme": request.theme
    }
    
    # Run the crew
    result = resume_crew.kickoff(inputs=inputs)
    
    # Read the output files generated by the tasks
    base_dir = os.path.dirname(os.path.abspath(__file__))
    
    def read_file(filename):
        path = os.path.join(base_dir, "output", filename)
        if os.path.exists(path):
            with open(path, "r", encoding="utf-8") as f:
                return f.read()
        return f"{filename} not found."

    resume_content = read_file("resume.md")
    ats_report_content = read_file("ats_report.md")
    improvement_plan_content = read_file("improvement_plan.md")
    
    return {
        "resume": resume_content,
        "ats_report": ats_report_content,
        "improvement_plan": improvement_plan_content
    }
