import os
import json
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from crew import resume_crew, job_scoring_crew

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ResumeRequest(BaseModel):
    profile: str
    job_description: str
    theme: str = "Modern"

@app.post("/api/generate")
def generate_resume(request: ResumeRequest):
    inputs = {
        "profile": request.profile,
        "job_description": request.job_description,
        "theme": request.theme
    }
    
    # Run the crew
    result = resume_crew.kickoff(inputs=inputs)
    
    # Read the output files generated by the tasks
    base_dir = os.path.dirname(os.path.abspath(__file__))
    
    def read_file(filename):
        path = os.path.join(base_dir, "output", filename)
        if os.path.exists(path):
            with open(path, "r", encoding="utf-8") as f:
                return f.read()
        return f"{filename} not found."

    resume_content = read_file("resume.md")
    ats_report_content = read_file("ats_report.md")
    improvement_plan_content = read_file("improvement_plan.md")
    cover_letter_content = read_file("cover_letter.md")
    linkedin_content = read_file("linkedin.md")
    interview_content = read_file("interview.md")
    
    return {
        "resume": resume_content,
        "ats_report": ats_report_content,
        "improvement_plan": improvement_plan_content,
        "cover_letter": cover_letter_content,
        "linkedin_about": linkedin_content,
        "interview_questions": interview_content
    }

@app.post("/api/jobs")
def get_jobs(request: ResumeRequest):
    mock_jobs = [
        {
            "id": 1,
            "company": "Google",
            "title": "Software Engineer, Backend",
            "location": "Remote",
            "description": "Looking for a backend engineer with Java, Python, and SQL experience. Must have strong DSA skills.",
            "apply_link": "https://careers.google.com"
        },
        {
            "id": 2,
            "company": "Startup Inc",
            "title": "Full Stack Developer",
            "location": "New York, NY",
            "description": "Need a developer experienced in React.js, Node.js, and MongoDB. Fast-paced environment.",
            "apply_link": "https://startup.com/jobs"
        },
        {
            "id": 3,
            "company": "FinTech Corp",
            "title": "Data Analyst",
            "location": "London, UK",
            "description": "Requires advanced Excel, Tableau, and financial modeling experience.",
            "apply_link": "https://fintech.com/careers"
        },
        {
            "id": 4,
            "company": "Tech Solutions",
            "title": "Java Spring Boot Developer",
            "location": "Pune, India",
            "description": "Looking for 1+ years experience in Java, Spring Boot, REST APIs, and MySQL.",
            "apply_link": "https://techsolutions.com/apply"
        }
    ]

    inputs = {
        "profile": request.profile,
        "jobs_json": json.dumps(mock_jobs)
    }

    result = job_scoring_crew.kickoff(inputs=inputs)

    try:
        clean_result = str(result).replace("```json", "").replace("```", "").strip()
        scores = json.loads(clean_result)
        
        score_dict = {item['id']: item['match_score'] for item in scores}
        for job in mock_jobs:
            job['match_score'] = score_dict.get(job['id'], 50)
            
        mock_jobs.sort(key=lambda x: x['match_score'], reverse=True)
    except Exception as e:
        print("Error parsing job scores:", e)
        for job in mock_jobs:
            job['match_score'] = 75
            
    return {"jobs": mock_jobs}
