import os
import io
import json
import requests
import re
from fastapi import FastAPI, UploadFile, File
import PyPDF2
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from crew import resume_crew, job_scoring_crew

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ResumeRequest(BaseModel):
    profile: str
    job_description: str
    theme: str = "Modern"

@app.post("/api/upload-pdf")
async def upload_pdf(file: UploadFile = File(...)):
    try:
        contents = await file.read()
        pdf_reader = PyPDF2.PdfReader(io.BytesIO(contents))
        extracted_text = ""
        for page in pdf_reader.pages:
            extracted_text += page.extract_text() + "\n"
        return {"extracted_text": extracted_text.strip()}
    except Exception as e:
        return {"error": str(e)}

@app.post("/api/generate")
def generate_resume(request: ResumeRequest):
    inputs = {
        "profile": request.profile,
        "job_description": request.job_description,
        "theme": request.theme
    }
    
    # Run the crew
    result = resume_crew.kickoff(inputs=inputs)
    
    # Read the output files generated by the tasks
    base_dir = os.path.dirname(os.path.abspath(__file__))
    
    def read_file(filename):
        path = os.path.join(base_dir, "output", filename)
        if os.path.exists(path):
            with open(path, "r", encoding="utf-8") as f:
                return f.read()
        return f"{filename} not found."

    resume_content = read_file("resume.json")
    ats_report_content = read_file("ats_report.md")
    improvement_plan_content = read_file("improvement_plan.md")
    cover_letter_content = read_file("cover_letter.md")
    linkedin_content = read_file("linkedin.md")
    interview_content = read_file("interview.md")
    
    return {
        "resume": resume_content,
        "ats_report": ats_report_content,
        "improvement_plan": improvement_plan_content,
        "cover_letter": cover_letter_content,
        "linkedin_about": linkedin_content,
        "interview_questions": interview_content
    }

@app.post("/api/jobs")
def get_jobs(request: ResumeRequest):
    import urllib.parse
    live_jobs = []
    
    # Extract search term from job description, fallback to general search
    search_term = "engineer"
    if request.job_description:
        words = request.job_description.split()[:3]
        search_term = " ".join(words)
        
    query = urllib.parse.quote(search_term)
    try:
        url = f"https://remotive.com/api/remote-jobs?search={query}&limit=10"
        response = requests.get(url)
        if response.status_code == 200:
            data = response.json()
            fetched_jobs = data.get("jobs", [])[:10]
            for i, j in enumerate(fetched_jobs):
                desc = re.sub('<[^<]+>', '', j.get("description", ""))[:300] + "..."
                live_jobs.append({
                    "id": j.get("id", i),
                    "company": j.get("company_name", "Unknown"),
                    "title": j.get("title", "Software Engineer"),
                    "location": j.get("candidate_required_location", "Remote"),
                    "description": desc,
                    "apply_link": j.get("url", "#")
                })
    except Exception as e:
        print("Failed to fetch live jobs:", e)

    # Fallback if API fails
    if not live_jobs:
        live_jobs = [
            {
                "id": 1,
                "company": "Google",
                "title": "Software Engineer, Backend",
                "location": "Remote",
                "description": "Looking for a backend engineer with Java, Python, and SQL experience. Must have strong DSA skills.",
                "apply_link": "https://careers.google.com"
            },
            {
                "id": 2,
                "company": "Startup Inc",
                "title": "Full Stack Developer",
                "location": "New York, NY",
                "description": "Need a developer experienced in React.js, Node.js, and MongoDB. Fast-paced environment.",
                "apply_link": "https://startup.com/jobs"
            }
        ]

    inputs = {
        "profile": request.profile,
        "jobs_json": json.dumps(live_jobs)
    }

    result = job_scoring_crew.kickoff(inputs=inputs)

    try:
        clean_result = str(result).replace("```json", "").replace("```", "").strip()
        scores = json.loads(clean_result)
        
        score_dict = {item['id']: item['match_score'] for item in scores}
        for job in live_jobs:
            job['match_score'] = score_dict.get(job['id'], 50)
            
        live_jobs.sort(key=lambda x: x['match_score'], reverse=True)
    except Exception as e:
        print("Error parsing job scores:", e)
        for job in live_jobs:
            job['match_score'] = 75
            
    return {"jobs": live_jobs}
